# Generated by Django 5.0.2 on 2024-03-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SymbiSharkTank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Signnup',
        ),
    ]
