# Generated by Django 5.0.2 on 2024-03-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SymbiSharkTank', '0002_rename_signup_signnup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signnup',
            new_name='SignUp',
        ),
    ]
