# Generated by Django 5.0.2 on 2024-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymbiSharkTank', '0003_rename_signnup_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_development_stage', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('unique_selling_proposition', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('product_photo', models.ImageField(upload_to='static/media/img/product_photos/')),
                ('product_video', models.FileField(upload_to='static/media/img/product_videos/')),
            ],
        ),
    ]
