# Generated by Django 5.0.2 on 2024-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymbiSharkTank', '0004_registration_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminatedUser_Round1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EliminatedUser_Round2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='financialdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('current_gross_profit_margin', models.CharField(max_length=100)),
                ('current_unit_manufacturing_cost', models.CharField(max_length=100)),
                ('growth_plan_percentage', models.CharField(max_length=100)),
                ('outstanding_debt', models.CharField(max_length=100)),
                ('current_revenue', models.CharField(max_length=100)),
                ('projected_revenue', models.CharField(max_length=100)),
                ('runway', models.CharField(max_length=100)),
                ('previous_funding_round', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Round2_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_development_stage', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('unique_selling_proposition', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Round3_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_development_stage', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('unique_selling_proposition', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('current_gross_profit_margin', models.CharField(max_length=100)),
                ('current_unit_manufacturing_cost', models.CharField(max_length=100)),
                ('growth_plan_percentage', models.CharField(max_length=100)),
                ('outstanding_debt', models.CharField(max_length=100)),
                ('current_revenue', models.CharField(max_length=100)),
                ('projected_revenue', models.CharField(max_length=100)),
                ('runway', models.CharField(max_length=100)),
                ('previous_funding_round', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
