# Generated by Django 5.0.2 on 2024-03-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymbiSharkTank', '0005_eliminateduser_round1_eliminateduser_round2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_details',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
